version: '3'

services:
  api:
    build:
      context: ./multcostura-back
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - ./multcostura-back/:/usr/app
      - /usr/app/node_modules
  nextjs:
    build:
      context: ./multcostura-front
      dockerfile: Dockerfile
  nginx:
    build: ./nginx
    ports:
      - 80:80
